{{- if or .Values.config.kasCaCert .Values.config.caCert }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitlab-agent.fullname" . }}
  labels:
    {{- include "gitlab-agent.labels" . | nindent 4 }}
data:
  ca.crt: {{ .Values.config.kasCaCert | default .Values.config.caCert | quote }}
{{- end }}
